apiVersion: batch/v1
kind: Job
metadata:
  name: hello-VERSION
spec:
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: say-hello
        image: fra.ocir.io/TENANCY_NAMESPACE/say-hello:latest
        imagePullPolicy: Always
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: ocirsecret
