version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: mikarinneoracle/pool
    environment:
      PATH: /home/circleci/bin:$(PATH)
      OCI_CLI_AUTH: instance_principal
    steps:
      - checkout
      - run:
          command: |
            export TENANCY_NAMESPACE=$(oci os ns get | jq .data | tr -d '"')
            oci raw-request --region eu-frankfurt-1 --http-method GET --target-uri 'https://fra.ocir.io/20180419/docker/token' --auth=instance_principal | jq -r .data.token | docker login -u BEARER_TOKEN --password-stdin fra.ocir.io
            VERSION=$(date +%Y-%m-%d-%H%M%S)
            docker pull hello-world
            docker tag hello-world fra.ocir.io/$TENANCY_NAMESPACE/say-hello:latest
            docker pull fra.ocir.io/$TENANCY_NAMESPACE/say-hello:latest
            docker run fra.ocir.io/$TENANCY_NAMESPACE/say-hello:latest
            # OKE cluster access is already configured on the runner and can be at ~/.kube/config
            sed "s|TENANCY_NAMESPACE|$TENANCY_NAMESPACE|g" -i hello.yaml
            sed "s|VERSION|$VERSION|g" -i hello.yaml
            kubectl apply -f hello.yaml
